---
# If you tag include_role tasks in here, you can selectively apply roles by setting the ANSIBLE_SKIP_TAGS environment variable:
# $ ANSIBLE_SKIP_TAGS="geerlingguy.nginx,geerlingguy.php" molecule converge
# Note multiple tags are seperated by a comma
#
- name: Converge
  hosts: all
  tasks:
    - name: create the molecule-test-logs log group
      cloudwatchlogs_log_group:
        state: present
        log_group_name: molecule-test-logs
        tags: {"Name": "molecule-test-logs", "Env": "infraqa"}
        retention: 3
      delegate_to: localhost

    - name: "Include the role we're developing"
      include_role:
        apply:
          become: true
        name: "ansible.cloudwatch-agent"
      vars:
        aws_cw_region: 'us-east-1'
        aws_cw_logfiles:
          - path: "/var/log/daemon.log"
            timestamp_format: "%b %d %H:%M:%S"
            log_group: "molecule-test-logs"
      tags:
        - ansible.cloudwatch-agent
