---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: ansible.cloudwatch-agent
    image: ami-083d24fb90054e5f0
    instance_type: t2.micro
    IAMrole: "SendLogsToCloudWatch"
    vpc_subnet_id: subnet-6183565f
    group: remote-workers
    instance_tags:
      Name: cloudwatch-agent-role-test
      environment: test
      provisioner: molecule
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
