---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-zipstream)
      become: true
      changed_when: false

    # this should be put in a common "aws" sectigo role, which is a dependency of this role
    - name: install things
      apt:
        pkg:
          - rsync
          - acl
          - net-tools
        update_cache: true
      become: true
